travis:
  secure:
    BINSTAR_TOKEN: a2OIx3dUbjZKdAJy7aNn5KK11qi+Eo411ACJqWZm7GsMl6tSbO2UBlI8RhSDgd8O3Qz8fznLGa8LUFPisuvyK35Opxl3Jql6i0L38HgPduzhxlgunLekj/Z3+vfdWqPWSAHOK01FCOomSHxiTX+o8giIrDN29iRl1fQvqOmykGRFpQjDLjg1yR352PN22KWSsdHNJ1jJZXe+os8EYDDKhKl/fd7nMggtQhAXtFufBecDHG4cEkMULFIx2qjWbyVMCk/TGIya3V5L0hUeKd93parzE8TX71Q7cXIOQixn5yvZXebGGgNwowxpBHsrhTFcapJnOA0f0MY2GNP+2qLfYsVo9Vlk6BTtNCW1vAnWnz01ifv/CWRwAHKXCfrNLxVlpLHWNqxOxio9rHRdnkjEA+rsJrKv1VtbT1y1rLSMJVZk2FBtUId398lCvp8WU3azVnoK+ZKhhLehNKeXxJxk4PpjJdYTFTqBTfT2IVHyU52JKkKJneBshtaf4c4tYqk7jQG3ODLbjbEkH9QlM8JbtyqJCSipQhJdKpKKeeATaRH1ysVdClHdm02jWJ/sJeeeEbI/ICeFscP4h7BHNQvkQo8jgu6BM43Rg0vGzUibQsBD0VVuFUiH7+Vary2Tuy18K4i3tL8rBCfvRjMX0A76jDkan/evOg1PB3mLuowYf9Y=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
