travis:
  secure:
    BINSTAR_TOKEN: QgnLZ0sD3LpIOOOKSsuMaiQhQFS0C95DJ0Eo16FzBgi0qiXkndx69hETgwm+XjNO4XGJWVffJWrVeYc4zXtAzlKxTOkhInz1N+h10U0xiGLRxi5bTkGln7fmtfUApFDOGnFt2SH5rsW59aoOmfmZndvjxaAt2ESS42FEaiCwkj9XRUXiOSL7snwqlfJnkkT8xTfsdVcHDw7I90ms8lvyHCJNNQOK/e6skxX/z9Xex5270BIbgmjEPbrGxlvJDLr9lhXC7lE9ocvx+CX1GAU4KJLVCT/QHHiVYCX4z+JcNI+Zy6g4lJxOYnrQNf/WKSennAsaQ5/OH4X565yLR6a3hHLD+p4BaBFaPbZIEqjUHF1+YKQoq3FTJpzW6x2l+zbeBQqO05UuTtNvww6y0hmYkYm4PEkzaYIsLbDMewQJ330nxpQsCaK/WjSYIBm4DKStxjA7/x4sPsWIZg5O48Jt7HdSSwvRz2Yw6eZXzs/VDNrPywXuKUCxqJjEGpHx85cixEcWabD9E4C5L6Lsk85lSf2m1Kw9EwcGBPXCAaNgA3dMLOB8S2cGr5Its+CLK0H3rwQQAzkuJQGt1IjHU0mfEMOK8uGcZB6d9hqaAKL05AqR8cf4k2vWIQwac0TN5Tw1RILd8Uks+sEohNOQ/8g4ub/FMoQXVLXGV1WvGaUSwYk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
