travis:
  secure:
    BINSTAR_TOKEN: RpBeDndY2bFVrIVc+D7i/SF2+oJ5gST0PpZaXDXNIbko8/Q0PSyv2cNbceZuUn6Em5JlS90KWACcr3dNJhOUhi1YuC7ROFgES6OKB75QF3DxOdINaXSDntli3LE1tsAtm8pGjCbDhX9fij0fnRlg9k9iYyx3huRpkURNlzACVdowDGVWzRCBximq2Dl9dSzsxfLnEvfCisy6ZeSkI1xJYezWl4j22pHKRPmFrHQ5/m6XxokfRjGHj03R1eEyThA8w0TcMIxxUXWSx+U01eEZ4duJNOyXEg2WXgLfhzc/CfCja0Ag7ZhIDv9T+uQgA+rdV1TV8wDSUcLDXWH1mYI/4GVppmTUNbpkCv1vlh8POjBl9zCWwSzvH85XZyccZlFCqW/MttQiuVD19lf3UPpAoZTaurI5oBUIf+3f/uv/Gx5Hi6R7wCmmLZyklV1R+6gpQxt2JfCVaqBdwJ/OZlq/UyOlxdtFduXYT7N8TIyFPxE4873Zmm8SOD+983PD6G19d1ekUQJ/zAaQmU/wcHc9UlZnCHc3SLmRGE8EeyVA5eHrQ3b/wfII6xkFsZXEwssfjhxldNM3a9uj3RFuIs9k5O8DFQoVV6zLC0fe6sfMKIOSZ01or8GpGFrY1yg9vH14+F4QJA7P2It9z6fgun8jEMl5CAhWXzNVgWhz/2ek9kE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
